FROM {{ base }}

ENV DISTRIBUTION_DIR /go/src/github.com/docker/distribution
ENV DOCKER_BUILDTAGS include_oss include_gcs

RUN apk add --no-cache \
    gcc \
    g++ \
    make \
    git

WORKDIR $DISTRIBUTION_DIR

RUN git clone https://github.com/docker/distribution $DISTRIBUTION_DIR \
  && cp $DISTRIBUTION_DIR/cmd/registry/config-dev.yml /etc/docker/registry/config.yml

RUN make PREFIX=/go clean binaries
